version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      nodejs:
        condition: service_healthy
  
  nodejs:
    build: ./nodejs
    volumes:
      - ./nodejs:/usr/src/app
    entrypoint: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  postgres:
    build: ./postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: andresn
      POSTGRES_PASSWORD: teste123
      POSTGRES_DB: postgres
    ports:
    - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -U andresn"]
      interval: 5s
      timeout: 10s
      retries: 3

volumes:
  postgres:
    driver: local